# nginx proxy address - http://172.17.0.1:51821

name: wireguard
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wireguard-server
    hostname: ${BASE_HOST_NAME:-wg}
    restart: always
    pull_policy: always
    privileged: true
    logging: *default-logging
    environment:
      LANG: en
      PORT: 51821
      HOST: 0.0.0.0
      INSECURE: true
      DISABLE_IPV6: false
      EXPERIMENTAL_AWG: false
      INIT_ENABLED: true
      INIT_PORT: 51820
      INIT_HOST: ${BASE_HOST_NAME:-wg}
      INIT_USERNAME: administrator
      INIT_PASSWORD: "${APP_ADMIN_PASS:-password}"
      INIT_DNS: 1.1.1.1,8.8.8.8,9.9.9.9
      INIT_IPV4_CIDR: 10.8.0.0/24
      INIT_IPV6_CIDR: fd42:42:42::/64
      INIT_ALLOWED_IPS: 0.0.0.0/0,::/0
    volumes:
      - '/lib/modules:/lib/modules'
      - '/usr/lib/modules:/usr/lib/modules'
      - './volumes/config/wireguard:/etc/wireguard'
    ports:
      - '51820:51820/udp'
      - '172.17.0.1:51821:51821/tcp'
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard

networks:
  wireguard:
    external: false
    name: wireguard
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.253.0/24
        - subnet: fddc:8ae0:5c95:ff8e::/64

