# nginx proxy address - http://172.17.0.1:51821

name: wireguard
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    hostname: ${BASE_HOST_NAME:-wg}
    restart: always
    pull_policy: always
    privileged: true
    logging: *default-logging
    environment:
      LANG: en
      PORT: 51821
      INSECURE: true
      HOST: ${0.0.0.0:-localhost}
      INIT_ENABLED: true
      DISABLE_IPV6: false
      EXPERIMENTAL_AWG: true
      INIT_ENABLED: true
      INIT_PORT: 51820
      INIT_ALLOWED_IPS: 0.0.0.0/0,::/0
      INIT_IPV4_CIDR: 192.168.253.0/24
      INIT_IPV6_CIDR: 2001:0DB8::/64
      INIT_DNS: 74.50.113.149,82.29.128.43,1.1.1.1
      INIT_USERNAME: administrator
      INIT_PASSWORD: "${APP_ADMIN_PASS:-password}"
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - '/lib/modules:/lib/modules'
      - '/usr/lib/modules:/usr/lib/modules'
      - './volumes/config/wireguard:/etc/wireguard'
    ports:
      - '51820:51820/udp'
      - '172.17.0.1:51821:51821/tcp'
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://wireguard:51821'
      - 'cloudflare.hostname=wireguard.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.wireguard.entrypoints=http'
      - 'traefik.http.routers.wireguard-secure.tls=true'
      - 'traefik.http.routers.wireguard.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.wireguard-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.wireguard.middlewares=wireguard-https-redirect'
      - 'traefik.http.routers.wireguard-secure.entrypoints=https'
      - 'traefik.http.routers.wireguard-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.wireguard-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.wireguard-secure.service=wireguard'
      - 'traefik.http.services.wireguard.loadbalancer.server.port=51821'

networks:
  wireguard:
    external: false
    name: wireguard
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.253.0/24
  proxy:
    external: true
  cloudflare:
    external: true
